my_django_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from my_app import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login', 'django.contrib.auth.views.login',name='login'),

    url(r'^$',views.home,name='home'),
    url(r'^guest$',views.guest,name='guest'),
    url(r'^loggedIn$',views.loggedIn,name='loggedIn'),
    url(r'^my_app/(?P<currency_id>\w+)/$', views.detail, name='detail'),
    url(r'^(?P<currency_id>\w+)/rates/$',views.exchange_rates,name='exch_rates'),
]

my_app/models.py
from django.db import models

# Create your models here.
class Currency(models.Model):
    identifier = models.CharField(max_length=3) #USD,EUR etc.
    long_name = models.CharField(max_length=50) #United States Dollar etc.
    date_added = models.DateTimeField() #When added to database
    def __str__(self):
        return self.identifier + " " + self.long_name

class Rates(models.Model):
    id_1 = models.ForeignKey(Currency) #A link to a Currency object
    id_2 = models.CharField(max_length=3) #Identifier for currency 2
    rate = models.FloatField(default=1.0) #exchange rate
    last_update_time = models.DateTimeField() #last time updated

    def __str__(self):
        return self.id_1.identifier + " " + self.id_2 + " " + str(self.rate)

    def time_since_last_update(self):
        from datetime import datetime,timezone
        now=datetime.now(timezone.utc)
        try:
            time_diff = now - self.last_update_time
        except:
            return "Never"
        return time_diff

from django.contrib.auth.models import User

class Investor(models.Model):
    user=models.OneToOneField(User)
    account_number=models.CharField(max_length=10)

    def __str__(self):
        return "Investor: " + str(self.user.username)

class Balances(models.Model):
    account_holder = models.ForeignKey(Investor)
    currency_id = models.CharField(max_length=3)
    value = models.FloatField(default=0.0)


### Step 1 - create your player model ###
class Player(models.Model):
    name = models.CharField(max_length=30)
    pos = models.CharField(max_length=30)
    stat1 = models.FloatField(null=True)
    stat2 = models.FloatField(null=True)
    stat3 = models.FloatField(null=True)
    stat4 = models.FloatField(null=True)
    stat5 = models.FloatField(null=True)
    stat6 = models.FloatField(null=True)
    stat7 = models.FloatField(null=True)
    stat8 = models.FloatField(null=True)
    #stat1 = models.CharField(max_length=30, blank=True, null=False)
    #stat2 = models.CharField(max_length=30, blank=True, null=False)
    #stat3 = models.CharField(max_length=30, blank=True, null=False)
    #stat4 = models.CharField(max_length=30, blank=True, null=False)
    #stat5 = models.CharField(max_length=30, blank=True, null=False)
    #stat6 = models.CharField(max_length=30, blank=True, null=False)
    #stat7 = models.CharField(max_length=30, blank=True, null=False)
    #stat8 = models.CharField(max_length=30, blank=True, null=False)
    def __str__(self):
        return self.name

my_app/views.py
from django.shortcuts import render, HttpResponse,get_object_or_404
from my_app.models import Currency, Investor, Player ### See 7 - import player model ###
# Create your views here.

### See 6.b - I am passing all of the Player objects into the template ###
def home1(request):
    context = dict()
    context['Players'] = Player.objects.all()
    return render(request,"home.html",context)

def home(request):
    context = dict()
    return render(request,"home1.html",context)

def guest(request):
    context = dict()
    currency_list = Currency.objects.all()
    context['currency_list'] = currency_list
    return render(request,"guest.html",context)

def loggedIn(request):
    context = dict()
    the_user = request.user
    investor = Investor.objects.get(user=the_user)
    context['investor'] = investor
    return render(request,'loggedIn.html',context)


def detail(request,currency_id):
    context=dict()
    currency = get_object_or_404(Currency,identifier=currency_id)
    context['currency']=currency
    print(currency)
    return render(request, 'detail.html', context)

def exchange_rates(request,currency_id):
    c=get_object_or_404(Currency,identifier=currency_id)
    amount=request.GET['Conversion_Amount']
    cross_c=c.rates_set.get(pk=request.GET['Cross_Currency_List'])
    try:
        float(amount)
    except:
        return render(request, 'detail.html', {'currency':c})
    output="The current conversion rate from " + currency_id + " to  " +cross_c.id_2
    output=output + " is: " + str(cross_c.rate)+". "
    output=output+ currency_id + ' ' + str(amount) + " is equal to " + cross_c.id_2 + ' '
    output=output+str(float(amount)*float(cross_c.rate))
    return HttpResponse(output)

templates/detail.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<center><h1>Currency: {{ currency.identifier }} </h1></center>
 <b>Identifier: </b>{{ currency.identifier }} <p>
     <b>Long Name: </b>{{ currency.long_name }} 
    <!--We'll use an html form to get a currency identifier and amount to be converted--> 
<p><b>Please select the cross rate and click on the convert button</b>  
<form name="rate_selection_form" action="{% url 'exch_rates' currency.identifier %}" method ="GET">
     <select name="Cross_Currency_List">
     {% for rates in currency.rates_set.all %} 
    <option name="rates" value={{ rates.id }}> {{ rates.id_2 }} </option> 
{% endfor %}
     </select>
     <input type="text" value="1" name="Conversion_Amount">
     <input type="submit" value="Convert" name="convert" />
    <input type="submit" value="Reset" name="reset" />
</form>
This is more complex stuff
</body>
</html>

templates/guest.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% if currency_list %}
    <!--Currency list will come from the python index function --> 
    <center><h1>Available currencies</h1><p> </center> 
    <ul>     {% for currency in currency_list %} 
        <li>
            <a href="/my_app/{{ currency.identifier }}/">{{ currency.long_name }}</a></li>
             {% endfor %} 
    </ul> 
{% else %} 
    <p>The list of currencies is empty..</p>
    {% endif %}

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<!-- See 8 - passing the Player objects into the template -->

    <table class="table table-striped" style="color:midnightblue">
        <tr>
            <th>Name</th>
            <th>Stat1</th>
            <th>Stat2</th>
            <th>Stat3</th>
            <th>Stat4</th>
            <th>Stat5</th>
            <th>Stat6</th>
            <th>Stat7</th>
        </tr>
            {% for object in Players %}
                <tr>
                    <td>{{ object.name }}</td>
                    <td>{{ object.stat1 }}</td>
                    <td>{{ object.stat2 }}</td>
                    <td>{{ object.stat3 }}</td>
                    <td>{{ object.stat4 }}</td>
                    <td>{{ object.stat5 }}</td>
                    <td>{{ object.stat6 }}</td>
                    <td>{{ object.stat7 }}</td>
                </tr>
            {% endfor %}
    </table>


</body>
</html>

templates/home1.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>Welcome to My App!</h1>
{% load staticfiles %}
<img src="{% static "currency_image.jpg" %}" alt="currency_image">

 <p>     Returning users: <a href="login">Login here</a> </p>
 <p>     New users: <a href="new_user">Register here</a> </p>
 <p>     Guests: <a href="guest">Click here</a> </p>  
</body>
</html>

templates/loggedIn.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<center><h1>Welcome {{ user }} </h1></center>
<h2>Your current balances:</h2><p>

<table style="width:30%">
 <tr>
  	<th bgcolor=gray>Currency</th>
  	<th bgcolor=gray>Value</th>
  {% for balance in investor.balances_set.all %}
	  <tr>
	    <td>{{balance.currency_id}}</td>
	    <td>{% load humanize %} {{ balance.value|floatformat:2|intcomma }}            </td>
	</tr>
  {% endfor %}
</table>
</center>
</body>
</html>